[build]
  publish = "dist"
  command = "npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF backend/ app.py"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  DISABLE_PYTHON = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
